const types = {
  SET_CUSTOMER: "@shop/SET_CUSTOMER",
  REQUEST_PIZZARIAS: "@shop/REQUEST_PIZZARIAS",
  SET_PIZZARIAS: "@shop/SET_PIZZARIAS",
  SET_PIZZARIA_MAP_SELECTED: "@shop/SET_PIZZARIA_MAP_SELECTED",
  SET_MAP_CENTER: "@shop/SET_MAP_CENTER",
  REQUEST_PIZZARIA: "@shop/REQUEST_PIZZARIA",
  SET_PIZZARIA: "@shop/SET_PIZZARIA",
  TOGGLE_CART_PRODUCT: "@shop/TOGGLE_CART_PRODUCT",
  SET_TRANSACTION: "@shop/SET_TRANSACTION",
  MAKE_PURCHASE: "@shop/MAKE_PURCHASE",
};

export default types;
